import runpod
from runpod.serverless.utils import rp_upload
import os
import websocket
import base64
import json
import uuid
import logging
import urllib.request
import urllib.parse
import urllib.error
import binascii # Base64 에러 처리를 위해 import
import subprocess
import shutil
import time
# 로깅 설정
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


server_address = os.getenv('SERVER_ADDRESS', '127.0.0.1')
client_id = str(uuid.uuid4())

# ---------------------------------------------------------------------------
# Workflow files
#   single image        : new_Wan22_api.json
#   start + end frame   : new_Wan22_flf2v_api.json
#   + prompt expansion  : *_expand_api.json (same graph + nodes 900/901)
# The expand variants are generated by tools/build_expand_workflows.py.
# ---------------------------------------------------------------------------
WORKFLOW_DIR = os.getenv("WORKFLOW_DIR", "/")
WORKFLOW_FILES = {
    ("i2v", False): "new_Wan22_api.json",
    ("i2v", True): "new_Wan22_expand_api.json",
    ("flf2v", False): "new_Wan22_flf2v_api.json",
    ("flf2v", True): "new_Wan22_flf2v_expand_api.json",
}

# Node ids shared by every workflow
NODE_TEXT_ENCODE = "135"
NODE_START_IMAGE = "244"
NODE_END_IMAGE = "617"
NODE_WIDTH = "235"
NODE_HEIGHT = "236"
NODE_RESIZE_START = "171"
NODE_PROMPT_GENERATOR = "900"    # WanVideoPromptGenerator (ComfyUI-MultiModal-Prompt-Nodes)
NODE_PROMPT_OUTPUT = "901"       # GVPromptOutput (custom_nodes/generate_video_prompt_nodes)

# Nodes needed to run *only* the prompt expansion (no video generation)
EXPAND_ONLY_NODES = (NODE_START_IMAGE, NODE_RESIZE_START, NODE_WIDTH, NODE_HEIGHT,
                     NODE_PROMPT_GENERATOR, NODE_PROMPT_OUTPUT)

# ---------------------------------------------------------------------------
# Prompt expansion defaults. All of these can be overridden per request via
# input.prompt_expansion or per endpoint via environment variables.
# ---------------------------------------------------------------------------
# Current ComfyUI refuses LoadImage paths outside its input directory (path
# traversal hardening in folder_paths.get_annotated_filepath), so every input
# image is staged under <input dir>/<task_id>/ and referenced relative to it.
COMFY_INPUT_DIR = os.getenv("COMFY_INPUT_DIR", "/ComfyUI/input")
DEFAULT_IMAGE = os.getenv("DEFAULT_IMAGE", "/example_image.png")
LLM_DIR = os.getenv("PROMPT_EXPANSION_LLM_DIR", "/ComfyUI/models/LLM")
# Second place the node looks (extra_model_paths.yaml lists it too): a Network
# Volume, which is where entrypoint.sh downloads the model on first start so the
# Docker build does not have to carry ~9 GB.
VOLUME_LLM_DIR = os.getenv("PROMPT_EXPANSION_VOLUME_LLM_DIR", "/runpod-volume/LLM")
EXPANSION_LANGUAGES = ("auto", "zh", "en")
EXPANSION_DEVICES = ("GPU", "CPU")
MULTIMODAL_NODE_DIR = os.getenv("MULTIMODAL_NODE_DIR", "/ComfyUI/custom_nodes/ComfyUI-MultiModal-Prompt-Nodes")

DEFAULT_NEGATIVE_PROMPT = ("bright tones, overexposed, static, blurred details, subtitles, style, works, paintings, images, "
                           "static, overall gray, worst quality, low quality, JPEG compression residue, ugly, incomplete, "
                           "extra fingers, poorly drawn hands, poorly drawn faces, deformed, disfigured, misshapen limbs, "
                           "fused fingers, still picture, messy background, three legs, many people in the background, "
                           "walking backwards")


class JobError(Exception):
    """Raised for user-facing problems (bad input, missing model, ComfyUI errors)."""


def to_nearest_multiple_of_16(value):
    """주어진 값을 가장 가까운 16의 배수로 보정, 최소 16 보장"""
    try:
        numeric_value = float(value)
    except Exception:
        raise JobError(f"width/height must be numeric, got: {value!r}")
    adjusted = int(round(numeric_value / 16.0) * 16)
    if adjusted < 16:
        adjusted = 16
    return adjusted
def task_input_dir(task_id):
    """Per-job staging folder inside ComfyUI's input directory."""
    return os.path.join(COMFY_INPUT_DIR, task_id)


def comfy_image_ref(path):
    """What to put in a LoadImage node for a staged file: the path relative to the
    ComfyUI input directory (required by current ComfyUI). Anything outside it is
    passed through unchanged for older builds that still accept absolute paths."""
    path = os.path.abspath(path)
    root = os.path.abspath(COMFY_INPUT_DIR)
    if path.startswith(root + os.sep):
        return os.path.relpath(path, root).replace(os.sep, "/")
    return path


def process_input(input_data, task_id, output_filename, input_type):
    """입력 데이터를 처리하여 파일 경로를 반환하는 함수 (always a file under the ComfyUI input dir)"""
    temp_dir = task_input_dir(task_id)
    if input_type == "path":
        # 경로인 경우: copy into the input dir so ComfyUI's LoadImage will accept it
        logger.info(f"📁 경로 입력 처리: {input_data}")
        if not os.path.isfile(input_data):
            raise JobError(f"image path not found on the worker: {input_data}")
        os.makedirs(temp_dir, exist_ok=True)
        file_path = os.path.abspath(os.path.join(temp_dir, output_filename))
        shutil.copyfile(input_data, file_path)
        return file_path
    elif input_type == "url":
        # URL인 경우 다운로드
        logger.info(f"🌐 URL 입력 처리: {input_data}")
        os.makedirs(temp_dir, exist_ok=True)
        file_path = os.path.abspath(os.path.join(temp_dir, output_filename))
        return download_file_from_url(input_data, file_path)
    elif input_type == "base64":
        # Base64인 경우 디코딩하여 저장
        logger.info(f"🔢 Base64 입력 처리")
        return save_base64_to_file(input_data, temp_dir, output_filename)
    else:
        raise JobError(f"Unsupported input type: {input_type}")

        
def download_file_from_url(url, output_path):
    """URL에서 파일을 다운로드하는 함수"""
    try:
        # wget을 사용하여 파일 다운로드
        result = subprocess.run([
            'wget', '-O', output_path, '--no-verbose', url
        ], capture_output=True, text=True)
        
        if result.returncode == 0:
            logger.info(f"✅ URL에서 파일을 성공적으로 다운로드했습니다: {url} -> {output_path}")
            return output_path
        else:
            logger.error(f"❌ wget 다운로드 실패: {result.stderr}")
            raise JobError(f"URL download failed: {result.stderr}")
    except subprocess.TimeoutExpired:
        logger.error("❌ 다운로드 시간 초과")
        raise JobError("URL download timed out")
    except JobError:
        raise
    except Exception as e:
        logger.error(f"❌ 다운로드 중 오류 발생: {e}")
        raise JobError(f"URL download error: {e}")


def strip_data_url_prefix(base64_data):
    """Accept both raw base64 and data URLs ("data:image/png;base64,....")."""
    if isinstance(base64_data, str) and base64_data.startswith("data:"):
        comma = base64_data.find(",")
        if comma != -1:
            return base64_data[comma + 1:]
    return base64_data


def save_base64_to_file(base64_data, temp_dir, output_filename):
    """Base64 데이터를 파일로 저장하는 함수"""
    try:
        # Base64 문자열 디코딩
        decoded_data = base64.b64decode(strip_data_url_prefix(base64_data))
        
        # 디렉토리가 존재하지 않으면 생성
        os.makedirs(temp_dir, exist_ok=True)
        
        # 파일로 저장
        file_path = os.path.abspath(os.path.join(temp_dir, output_filename))
        with open(file_path, 'wb') as f:
            f.write(decoded_data)
        
        logger.info(f"✅ Base64 입력을 '{file_path}' 파일로 저장했습니다.")
        return file_path
    except (binascii.Error, ValueError) as e:
        logger.error(f"❌ Base64 디코딩 실패: {e}")
        raise JobError(f"Base64 decoding failed: {e}")
    
def queue_prompt(prompt):
    url = f"http://{server_address}:8188/prompt"
    logger.info(f"Queueing prompt to: {url}")
    p = {"prompt": prompt, "client_id": client_id}
    data = json.dumps(p).encode('utf-8')
    req = urllib.request.Request(url, data=data)
    try:
        return json.loads(urllib.request.urlopen(req).read())
    except urllib.error.HTTPError as e:
        # ComfyUI answers 400 with a JSON body describing which node/input failed
        # validation (e.g. an LLM model name that is not in the node's list).
        body = e.read().decode("utf-8", "replace")
        raise JobError(f"ComfyUI rejected the workflow: {summarize_validation_error(body)}")


def summarize_validation_error(body):
    try:
        data = json.loads(body)
    except Exception:
        return body[:2000]
    parts = []
    err = data.get("error") or {}
    if isinstance(err, dict) and err.get("message"):
        parts.append(err["message"])
    for node_id, info in (data.get("node_errors") or {}).items():
        class_type = info.get("class_type", "?")
        for e in info.get("errors", []):
            msg = e.get("message", "")
            details = e.get("details", "")
            parts.append(f"node {node_id} ({class_type}): {msg} {details}".strip())
    return "; ".join(parts) or body[:2000]

def get_image(filename, subfolder, folder_type):
    url = f"http://{server_address}:8188/view"
    logger.info(f"Getting image from: {url}")
    data = {"filename": filename, "subfolder": subfolder, "type": folder_type}
    url_values = urllib.parse.urlencode(data)
    with urllib.request.urlopen(f"{url}?{url_values}") as response:
        return response.read()

def get_history(prompt_id):
    url = f"http://{server_address}:8188/history/{prompt_id}"
    logger.info(f"Getting history from: {url}")
    with urllib.request.urlopen(url) as response:
        return json.loads(response.read())

def run_workflow(ws, prompt):
    """Queue the graph, wait for it to finish and collect videos and texts.

    Returns (videos, texts, error) where videos/texts map node_id -> list and
    error is a human readable string if ComfyUI reported an execution error.
    """
    prompt_id = queue_prompt(prompt)['prompt_id']
    error = None
    while True:
        out = ws.recv()
        if isinstance(out, str):
            message = json.loads(out)
            mtype = message.get('type')
            data = message.get('data') or {}
            if mtype == 'executing':
                if data.get('node') is None and data.get('prompt_id') == prompt_id:
                    break
            elif mtype == 'execution_error' and data.get('prompt_id') == prompt_id:
                error = (f"node {data.get('node_id')} ({data.get('node_type')}): "
                         f"{data.get('exception_type', '')} {data.get('exception_message', '')}").strip()
                logger.error(f"ComfyUI execution error: {error}")
            elif mtype == 'execution_interrupted' and data.get('prompt_id') == prompt_id:
                error = "execution interrupted"
        else:
            continue

    history = get_history(prompt_id).get(prompt_id, {})
    status = history.get('status') or {}
    if error is None and status.get('status_str') == 'error':
        error = "execution failed (see worker logs)"
    output_videos = {}
    output_texts = {}
    for node_id, node_output in history.get('outputs', {}).items():
        videos_output = []
        if 'gifs' in node_output:
            for video in node_output['gifs']:
                # fullpath를 이용하여 직접 파일을 읽고 base64로 인코딩
                with open(video['fullpath'], 'rb') as f:
                    video_data = base64.b64encode(f.read()).decode('utf-8')
                videos_output.append(video_data)
        if videos_output:
            output_videos[node_id] = videos_output
        if 'text' in node_output:
            output_texts[node_id] = [t for t in node_output['text'] if isinstance(t, str)]

    return output_videos, output_texts, error


def get_videos(ws, prompt):
    """Backwards compatible wrapper around run_workflow()."""
    videos, _, _ = run_workflow(ws, prompt)
    return videos

def load_workflow(workflow_path):
    with open(workflow_path, 'r') as file:
        return json.load(file)


# ---------------------------------------------------------------------------
# Prompt expansion helpers
# ---------------------------------------------------------------------------
def _node_model_name(path, models_dir):
    """Mirror the node's to_models_relative_path(): relative to ComfyUI/models when
    the file lives there, otherwise the absolute path (Network Volume)."""
    path = os.path.normpath(path)
    models_dir = os.path.normpath(models_dir)
    if path.startswith(models_dir + os.sep):
        return os.path.relpath(path, models_dir).replace(os.sep, "/")
    return path.replace(os.sep, "/")


def list_local_llm_models(llm_dir=None, extra_dirs=None):
    """GGUF files the Wan Video Prompt Generator would list as 'Local: <name>'.

    Image models come out as 'LLM/<file>', Network Volume models as
    '/runpod-volume/LLM/<file>' — exactly the combo values the node builds.
    """
    llm_dir = llm_dir or LLM_DIR
    dirs = [llm_dir] + list(extra_dirs if extra_dirs is not None else [VOLUME_LLM_DIR])
    models_dir = os.path.dirname(os.path.normpath(llm_dir))
    names = []
    for d in dirs:
        if not d or not os.path.isdir(d):
            continue
        for root, _, files in os.walk(d):
            for f in files:
                lower = f.lower()
                if not lower.endswith(".gguf") or lower.startswith("mmproj") or "qwen" not in lower:
                    continue
                names.append(_node_model_name(os.path.join(root, f), models_dir))
    return sorted(set(names), key=str.lower)


def default_llm_model(llm_dir=None):
    env = os.getenv("PROMPT_EXPANSION_MODEL")
    if env:
        return normalize_llm_model(env)
    models = list_local_llm_models(llm_dir)
    if not models:
        return None
    # Prefer the model the image was configured to fetch (PROMPT_LLM_URL) when
    # several are present, e.g. the stock Qwen3-VL next to the abliterated one
    # on a volume that predates the switch.
    configured = os.path.basename(os.getenv("PROMPT_LLM_URL", "").split("?")[0]).lower()
    for m in models:
        if configured and os.path.basename(m).lower() == configured:
            return f"Local: {m}"
    return f"Local: {models[0]}"


def normalize_llm_model(value):
    """Turn user friendly spellings into the exact combo value the node expects.

    "Local: LLM/x.gguf"          -> unchanged
    "LLM/x.gguf"                 -> "Local: LLM/x.gguf"
    "/runpod-volume/LLM/x.gguf"  -> "Local: /runpod-volume/LLM/x.gguf"
    "x.gguf"                     -> whichever discovered model has that filename,
                                    else "Local: LLM/x.gguf"
    "qwen3.7-plus"               -> unchanged (DashScope cloud model)
    """
    value = str(value).strip()
    if value.startswith("Local: "):
        return value
    if value.lower().endswith(".gguf"):
        if "/" not in value:
            for name in list_local_llm_models():
                if os.path.basename(name).lower() == value.lower():
                    return f"Local: {name}"
            value = f"{os.path.basename(LLM_DIR.rstrip('/'))}/{value}"
        return f"Local: {value}"
    return value


def resolve_prompt_expansion(job_input):
    """Normalise the request's prompt expansion settings.

    Accepted forms:
        "prompt_expansion": true
        "prompt_expansion": {"language": "zh", "model": "...", "device": "GPU", ...}
        "expand_prompt": true                (shorthand)
        "expand_only": true                  (implies expansion; skips video generation)

    Returns None when expansion is off, otherwise a dict with the node inputs.
    """
    raw = job_input.get("prompt_expansion")
    if raw is None:
        raw = job_input.get("expand_prompt")
    expand_only = bool(job_input.get("expand_only", False))
    if raw is None:
        raw = expand_only
    if isinstance(raw, bool):
        raw = {"enabled": raw}
    if not isinstance(raw, dict):
        raise JobError("prompt_expansion must be a boolean or an object")
    enabled = bool(raw.get("enabled", True)) or expand_only
    if not enabled:
        return None

    language = str(raw.get("language", os.getenv("PROMPT_EXPANSION_LANGUAGE", "zh"))).lower()
    if language not in EXPANSION_LANGUAGES:
        raise JobError(f"prompt_expansion.language must be one of {EXPANSION_LANGUAGES}, got {language!r}")

    device = str(raw.get("device", os.getenv("PROMPT_EXPANSION_DEVICE", "GPU"))).upper()
    if device not in EXPANSION_DEVICES:
        raise JobError(f"prompt_expansion.device must be one of {EXPANSION_DEVICES}, got {device!r}")

    model = raw.get("model")
    model = normalize_llm_model(model) if model else default_llm_model()
    if not model:
        raise JobError(f"No local prompt model found in {LLM_DIR} or {VOLUME_LLM_DIR} and no "
                       "prompt_expansion.model / PROMPT_EXPANSION_MODEL given. Let entrypoint.sh download "
                       "the bundled model (needs a Network Volume or PROMPT_LLM_URL), drop a Qwen GGUF plus "
                       "mmproj in the LLM folder, or pass a DashScope model name.")
    if not model.startswith("Local: "):
        key_path = os.path.join(MULTIMODAL_NODE_DIR, "api_key.txt")
        if not os.path.isfile(key_path) or not open(key_path, encoding="utf-8").read().strip():
            raise JobError(f"prompt_expansion.model {model!r} is a DashScope cloud model but no API key is "
                           "configured. Set the DASHSCOPE_API_KEY environment variable on the endpoint.")

    try:
        max_retries = int(raw.get("max_retries", 3))
    except (TypeError, ValueError):
        raise JobError("prompt_expansion.max_retries must be an integer")
    max_retries = min(max(max_retries, 1), 10)

    return {
        "language": language,
        "model": model,
        "mmproj": str(raw.get("mmproj", "(Auto-detect)")),
        "device": device,
        "max_retries": max_retries,
        "save_tokens": bool(raw.get("save_tokens", True)),
    }


def apply_prompt_expansion(prompt, user_prompt, expansion):
    node = prompt[NODE_PROMPT_GENERATOR]["inputs"]
    node["prompt"] = user_prompt
    node["task_type"] = "Image-to-Video"
    node["target_language"] = expansion["language"]
    node["llm_model"] = expansion["model"]
    node["mmproj"] = expansion["mmproj"]
    node["max_retries"] = expansion["max_retries"]
    node["device"] = expansion["device"]
    node["save_tokens"] = expansion["save_tokens"]
    node["image"] = [NODE_RESIZE_START, 0]
    prompt[NODE_TEXT_ENCODE]["inputs"]["positive_prompt"] = [NODE_PROMPT_OUTPUT, 0]
    logger.info(f"Prompt expansion enabled: model={expansion['model']} language={expansion['language']} "
                f"device={expansion['device']}")


def expand_only_graph(prompt):
    """Keep just the nodes needed to load the image and expand the prompt."""
    return {nid: prompt[nid] for nid in EXPAND_ONLY_NODES if nid in prompt}


def build_workflow(job_input, image_path, end_image_path_local, expansion=None):
    """Turn a request into a ComfyUI API-format graph. Pure: no network access."""
    if "prompt" not in job_input:
        raise JobError("'prompt' is required")

    # LoRA 설정 확인 - 배열로 받아서 처리
    lora_pairs = job_input.get("lora_pairs", []) or []
    
    # 최대 4개 LoRA까지 지원
    if len(lora_pairs) > 4:
        logger.warning(f"LoRA 개수가 {len(lora_pairs)}개입니다. 최대 4개까지만 지원됩니다. 처음 4개만 사용합니다.")
        lora_pairs = lora_pairs[:4]
    lora_count = len(lora_pairs)
    
    # 워크플로우 파일 선택 (end_image_*가 있으면 FLF2V 워크플로 사용)
    mode = "flf2v" if end_image_path_local else "i2v"
    workflow_file = os.path.join(WORKFLOW_DIR, WORKFLOW_FILES[(mode, expansion is not None)])
    logger.info(f"Using {'FLF2V' if end_image_path_local else 'single'} workflow ({os.path.basename(workflow_file)}) "
                f"with {lora_count} LoRA pairs")
    
    prompt = load_workflow(workflow_file)
    
    length = job_input.get("length", 81)
    steps = job_input.get("steps", 10)

    prompt[NODE_START_IMAGE]["inputs"]["image"] = comfy_image_ref(image_path)
    prompt["541"]["inputs"]["num_frames"] = length
    prompt[NODE_TEXT_ENCODE]["inputs"]["positive_prompt"] = job_input["prompt"]
    prompt[NODE_TEXT_ENCODE]["inputs"]["negative_prompt"] = job_input.get("negative_prompt", DEFAULT_NEGATIVE_PROMPT)
    seed = job_input.get("seed", 42)
    prompt["220"]["inputs"]["seed"] = seed
    prompt["540"]["inputs"]["seed"] = seed
    prompt["540"]["inputs"]["cfg"] = job_input.get("cfg", 2.0)
    # 해상도(폭/높이) 16배수 보정
    original_width = job_input.get("width", 480)
    original_height = job_input.get("height", 832)
    adjusted_width = to_nearest_multiple_of_16(original_width)
    adjusted_height = to_nearest_multiple_of_16(original_height)
    if adjusted_width != original_width:
        logger.info(f"Width adjusted to nearest multiple of 16: {original_width} -> {adjusted_width}")
    if adjusted_height != original_height:
        logger.info(f"Height adjusted to nearest multiple of 16: {original_height} -> {adjusted_height}")
    prompt[NODE_WIDTH]["inputs"]["value"] = adjusted_width
    prompt[NODE_HEIGHT]["inputs"]["value"] = adjusted_height
    prompt["498"]["inputs"]["context_overlap"] = job_input.get("context_overlap", 48)
    prompt["498"]["inputs"]["context_frames"] = length

    # step 설정 적용
    if "834" in prompt:
        prompt["834"]["inputs"]["steps"] = steps
        logger.info(f"Steps set to: {steps}")
        lowsteps = int(steps*0.6)
        prompt["829"]["inputs"]["step"] = lowsteps
        logger.info(f"LowSteps set to: {lowsteps}")

    # 엔드 이미지가 있는 경우 617번 노드에 경로 적용 (FLF2V 전용)
    if end_image_path_local:
        prompt[NODE_END_IMAGE]["inputs"]["image"] = comfy_image_ref(end_image_path_local)
    
    # LoRA 설정 적용 - HIGH LoRA는 노드 279, LOW LoRA는 노드 553
    if lora_count > 0:
        # HIGH LoRA 노드 (279번)
        high_lora_node_id = "279"
        
        # LOW LoRA 노드 (553번)
        low_lora_node_id = "553"
        
        # 입력받은 LoRA pairs 적용 (lora_1부터 시작)
        for i, lora_pair in enumerate(lora_pairs):
            if i < 4:  # 최대 4개까지만
                lora_high = lora_pair.get("high")
                lora_low = lora_pair.get("low")
                lora_high_weight = lora_pair.get("high_weight", 1.0)
                lora_low_weight = lora_pair.get("low_weight", 1.0)
                
                # HIGH LoRA 설정 (노드 279번, lora_1부터 시작)
                if lora_high:
                    prompt[high_lora_node_id]["inputs"][f"lora_{i+1}"] = lora_high
                    prompt[high_lora_node_id]["inputs"][f"strength_{i+1}"] = lora_high_weight
                    logger.info(f"LoRA {i+1} HIGH applied to node 279: {lora_high} with weight {lora_high_weight}")
                
                # LOW LoRA 설정 (노드 553번, lora_1부터 시작)
                if lora_low:
                    prompt[low_lora_node_id]["inputs"][f"lora_{i+1}"] = lora_low
                    prompt[low_lora_node_id]["inputs"][f"strength_{i+1}"] = lora_low_weight
                    logger.info(f"LoRA {i+1} LOW applied to node 553: {lora_low} with weight {lora_low_weight}")

    # 프롬프트 확장 (WanVideoPromptGenerator -> GVPromptOutput -> TextEncode)
    if expansion is not None:
        apply_prompt_expansion(prompt, job_input["prompt"], expansion)

    return prompt


def wait_for_comfyui():
    ws_url = f"ws://{server_address}:8188/ws?clientId={client_id}"
    logger.info(f"Connecting to WebSocket: {ws_url}")
    
    # 먼저 HTTP 연결이 가능한지 확인
    http_url = f"http://{server_address}:8188/"
    logger.info(f"Checking HTTP connection to: {http_url}")
    
    # HTTP 연결 확인 (최대 1분)
    max_http_attempts = 180
    for http_attempt in range(max_http_attempts):
        try:
            response = urllib.request.urlopen(http_url, timeout=5)
            logger.info(f"HTTP 연결 성공 (시도 {http_attempt+1})")
            break
        except Exception as e:
            logger.warning(f"HTTP 연결 실패 (시도 {http_attempt+1}/{max_http_attempts}): {e}")
            if http_attempt == max_http_attempts - 1:
                raise Exception("ComfyUI 서버에 연결할 수 없습니다. 서버가 실행 중인지 확인하세요.")
            time.sleep(1)
    
    ws = websocket.WebSocket()
    # 웹소켓 연결 시도 (최대 3분)
    max_attempts = int(180/5)  # 3분 (1초에 한 번씩 시도)
    for attempt in range(max_attempts):
        try:
            ws.connect(ws_url)
            logger.info(f"웹소켓 연결 성공 (시도 {attempt+1})")
            break
        except Exception as e:
            logger.warning(f"웹소켓 연결 실패 (시도 {attempt+1}/{max_attempts}): {e}")
            if attempt == max_attempts - 1:
                raise Exception("웹소켓 연결 시간 초과 (3분)")
            time.sleep(5)
    return ws


def handler(job):
    job_input = job.get("input", {})

    # Never log base64 payloads in full
    logger.info("Received job input: " + json.dumps(
        {k: (f"<{len(v)} chars>" if isinstance(v, str) and len(v) > 200 else v) for k, v in job_input.items()},
        ensure_ascii=False, default=str))
    task_id = f"task_{uuid.uuid4()}"

    try:
        # 이미지 입력 처리 (image_path, image_url, image_base64 중 하나만 사용)
        image_path = None
        if "image_path" in job_input:
            image_path = process_input(job_input["image_path"], task_id, "input_image.jpg", "path")
        elif "image_url" in job_input:
            image_path = process_input(job_input["image_url"], task_id, "input_image.jpg", "url")
        elif "image_base64" in job_input:
            image_path = process_input(job_input["image_base64"], task_id, "input_image.jpg", "base64")
        else:
            # 기본값 사용
            image_path = process_input(DEFAULT_IMAGE, task_id, "input_image.png", "path")
            logger.info(f"기본 이미지 파일을 사용합니다: {DEFAULT_IMAGE}")

        # 엔드 이미지 입력 처리 (end_image_path, end_image_url, end_image_base64 중 하나만 사용)
        end_image_path_local = None
        if "end_image_path" in job_input:
            end_image_path_local = process_input(job_input["end_image_path"], task_id, "end_image.jpg", "path")
        elif "end_image_url" in job_input:
            end_image_path_local = process_input(job_input["end_image_url"], task_id, "end_image.jpg", "url")
        elif "end_image_base64" in job_input:
            end_image_path_local = process_input(job_input["end_image_base64"], task_id, "end_image.jpg", "base64")

        expansion = resolve_prompt_expansion(job_input)
        expand_only = bool(job_input.get("expand_only", False))

        prompt = build_workflow(job_input, image_path, end_image_path_local, expansion)
        if expand_only:
            prompt = expand_only_graph(prompt)
            logger.info("expand_only: running prompt expansion without video generation")

        ws = wait_for_comfyui()
        try:
            videos, texts, error = run_workflow(ws, prompt)
        finally:
            ws.close()

        expanded_prompt = None
        if expansion is not None:
            for t in texts.get(NODE_PROMPT_OUTPUT, []):
                expanded_prompt = t
                break

        if expand_only:
            if expanded_prompt is None:
                raise JobError(error or "Prompt expansion produced no text")
            logger.info(f"Expanded prompt: {expanded_prompt}")
            return {"expanded_prompt": expanded_prompt, "prompt": job_input["prompt"]}

        # 이미지가 없는 경우 처리
        for node_id in videos:
            if videos[node_id]:
                result = {"video": videos[node_id][0]}
                if expansion is not None:
                    result["expanded_prompt"] = expanded_prompt
                    result["prompt"] = job_input["prompt"]
                return result

        raise JobError(error or "Video not found in ComfyUI output")

    except JobError as e:
        logger.error(f"Job failed: {e}")
        return {"error": str(e)}
    finally:
        # staged input images are per job; don't let them pile up in ComfyUI/input
        shutil.rmtree(task_input_dir(task_id), ignore_errors=True)


if __name__ == "__main__":
    runpod.serverless.start({"handler": handler})
